version: "3.7"
services:
  mysql:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=vignesh
      - MYSQL_DATABASE=NECCustomerDB2023
    volumes:
      - /data/mysql
    networks:
      - default
    healthcheck:
      interval: 30s
      timeout: 10s
      retries: 5
  server:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - mysql
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 15
        window: 50s
    networks:
      - default
    ports:
      - "7072:7072"
volumes:
  data: